### ISSUE TITLE
DB_Auth don't work

### ISSUE THREAD

**Issue by JoachimKunz** [phutchins/logstash-input-mongodb#11]
Hi.

I've got a problem regarding the authentication with the MongoDB.

The tools I use:
* MongoDB: 3.0.6
* Elasticsearch: 1.7.2
* Logstash: 1.5.4
* logstash-input-mongodb: logstash-input-mongodb-0.2.0.gem

This is the output of my log file containing the problem:
```
D, [2015-09-15T14:13:25.455000 #21908] DEBUG -- : MONGODB | Adding team-db1:27017 to the cluster.
D, [2015-09-15T14:13:25.480000 #21908] DEBUG -- : MONGODB | Adding team-db2:27017 to the cluster.
D, [2015-09-15T14:13:25.523000 #21908] DEBUG -- : MONGODB | Server team-db1:27017 discovered as primary in replica set: 'team_replSet'. Changing topology to replica set.
D, [2015-09-15T14:13:25.558000 #21908] DEBUG -- : MONGODB | team-db1:27017 | team.listCollections | STARTED | {"listCollections"=>1, "cursor"=>{}, "filter"=>{:name=>{"$not"=>/system\.|\$/}}}
D, [2015-09-15T14:13:25.561000 #21908] DEBUG -- : MONGODB | team-db1:27017 | team.listCollections | FAILED | not authorized on team to execute command { listCollections: 1, cursor: {}, filter: { name: { $not: /system\.|\$/ } } } (13) | 0.002s
The error reported is:
  not authorized on team to execute command { listCollections: 1, cursor: {}, filter: { name: { $not: /system\.|\$/ } } } (13)
```
My logstash Config:
```
input {
  mongodb {
    uri => "mongodb://admin:****@team-db1,team-db2/team"
    placeholder_db_dir => '/opt/logstash-mongodb/'
    placeholder_db_name => 'auftraggeber.db'
    collection => 'auftraggeber'
    batch_size => 5000
  }
}

output {
  elasticsearch {
    host => ["team-es2:9300"]
    cluster => 'team-es-cluster'
    index =>  'auftraggebers'
  }
}
```
The password contains a comma. To escape the comma I have used url-encode (%2C).
The authenticationDatabase I use is admin.

If I remove the username and password in the Logstash config, I get the same error.

**Comment by gatoatigrado** [comment]
++, I found a way to work around this issue, just change

https://github.com/phutchins/logstash-input-mongodb/blob/master/lib/logstash/inputs/mongodb.rb#L163

to read

```
conn = Mongo::Client.new(@uri)
```

not sure what the manual uri parsing stuff is about anyway.

**Comment by phutchins** [comment]
The URI parser is intended to grab the ssl true or false bit from the URI so that the plugin can error intelligently if required SSL files do not exist. This may not be needed at this point so I may test with it removed.

Are you using SSL with the fix that you applied @gatoatigrado ?

**Comment by phutchins** [comment]
@gatoatigrado The idea behind manual URI parsing is to be able to abstract away the mongo URI from the user in the Logstash config.

At this point I'm find with simply using the URI and letting the user figure out everything from there.

I still however can't seem to get auth working with the simple conn = Mongo::Client.new(@uri) which you've described. I attempted to get things working this way in the beginning but had no luck. Are you doing anything interesting with the URI and specifying admin database for auth?

**Comment by phutchins** [comment]
Fixed. Closing.
