### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by fshort** [phutchins/logstash-input-mongodb#12]
Am trying to configure this plugin to connect to my mongo replica set and am getting the following error: "not authorized for query on uilogs.system.namespace (13)"

From the mongo logs, reports something similar: "assertion 13 not authorized for query on uilogs.system.namespaces ns:uilogs.system.namespaces query: { name: $not: /system\.|\$/ } }"

My conf file looks like this:
...
mongodb {
  uri => 'mongodb://uilogsAdmin:<pswd>@host-abc123:27017/uilogs'
  placeholder_db_dir => '/home/somewhere/logstash-1.5.3/logstash-mongodb'
  placeholder_db_name => 'logstatsh_sqlite.db'
  collection => 'daily.apps'
}

am using logstash 1.5.3, the most recent version of this plugin 0.2.0, and mongodb 2.6.4

the login id 'uilogsAdmin' currently has the following roles: dbOwner, clusterAdmin, dbAdminAnyDatabase.

If I log into the primary with the above id and run uilogs.system.namespaces.find() I do not get the auth error.

Please advise what could be wrong here.

**Comment by phutchins** [comment]
This should be fixed in 0.3.2. Please give it a shot and let me know if it works for you @fshort. Thanks!

**Comment by phutchins** [comment]
Closing. Please let me know if this did not fix the issue for you.
