### ISSUE TITLE
Retain complex JSON structure from Mongo

### ISSUE THREAD

**Issue by snagajot** [phutchins/logstash-input-mongodb#14]
@phutchins My mongo contains complex nested JSON documents that I am trying to index into Elastic search (with a predefined mapping). By using the plugin in either 'flatten' or 'dig' mode, the complex JSON structure is lost. For example, array of nested json documents are represented as a string so Elastic does apply the mapping against it. 

Any thoughts on how to retain the structure from Mongo without any flattening ?

Thanks!

**Comment by gairom** [comment]
wrote a simple parse method to support, you can close the issue.

**Comment by phutchins** [comment]
You should be able to not use either flatten or dig and get the original
structure. I have not tested it in this way although I designed it to be
able to do this for use cases like yours. Did you try it that way? I'd like
to have the plugin be able to support your use case without a complex
config if possible...

**Comment by snagajot** [comment]
@phutchins @gairom I was able to remove references to flatten/dig methods and simply write the event to the queue although I had to change the codec to 'Json'. Below is my version of the cursor loop in 'run' method -

          cursor.each do |doc|
			logdate = DateTime.parse(doc['_id'].generation_time.to_s)
            #event = LogStash::Event.new("message" => doc.to_h.to_json.to_s)
			@codec.decode(doc.to_h.to_json.to_s) do |event|
			event["logdate"] = logdate.iso8601
			decorate(event)
            queue << event
			end
