### ISSUE TITLE
Logstash & ES 2.0 support

### ISSUE THREAD

**Issue by gairom** [phutchins/logstash-input-mongodb#17]
Hi,
Is anyone tested this input with the new Logstash 2.0 version?
I want to upgrade soon...
Thanks.

**Comment by eromoe** [comment]
can not install

**Comment by phutchins** [comment]
@gairom, I've tested installing in Logstash 2.1.1 via bin/plugin install logstash-input-mongodb-0.3.1.gem and it installed without issue. 

@eromoe, there's not much I can do to help you if you do not include any details. I'm closing this issue so if you are still having issues, please re-open.
