### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by euge-g** [phutchins/logstash-input-mongodb#20]
Thank you for the plugin, so far it works well and was quick to set up.

I have many fields that contain other fields and are nested to many levels. For example a field may contain the following:
```
"[{\"Field_1\"=>\"Field_1_Value\", \"Field_2\"=>\"Field_2_Value\", \"Field_3\"=>\"Field_3_Value\", \"Field_4\"=>\"Field_4_Value\", \"Field_5\"=>\"Field_5_Value\", \"Parent_Field\"=>[{\"Child_Field_1\"=>\"Child_Field_1_Value\", \"Child_Field_2\"=>nil, \"Child_Field_3\"=>\"Child_Field_3_Value\", \"Child_Field_4\"=>nil}]}]"
```
Is there a way to either have the plugin parse the contents as children of the parent field, or if there are existing filters that can parse the data properly?

I'm currently looking into using the ruby filter to iterate through the contents, but thought maybe I missed something and maybe there is something out there that can already do this.

Thanks

**Comment by phutchins** [comment]
Hello @euge-g, thanks for your positive input! I'm very happy that you've found use in this plugin.

For nested fields, you should simply be able to not use flatten or dig and get the original structure passed in from the plugin to Logstash.

To preserve that structure in JSON as it goes through Logstash, you might be able to filter the field as JSON (if it's in JSON format).

Link: https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html

If it's not in JSON, you may also want to look into the KV filter which is Key Value. I've not done this specifically with KV but it's worth looking into. I would think that you could use KV to get the parent key then use a filter to parse it's value as JSON or something along those lines...

Let me know what you find! I'll leave this open for a bit until I hear back...

**Comment by phutchins** [comment]
Haven't heard back so I assume you got it working. If you're still stuck, feel free to comment again and I'll do what I can to help! Closing.

**Comment by thejeff77** [comment]
I have this issue no matter what parse method I use. Sub fields still have the sort of escaped json-like syntax with the => instead of the ':' . I am not sure what kind of syntax this is, but it isn't valid json. Can you re-open this?

**Comment by thejeff77** [comment]
Yes the json parse filter fails to parse this syntax.
