### ISSUE TITLE
deleting mongodb documents doesn't get removed in ElasticSearch(ES)

### ISSUE THREAD

**Issue by chakrip82** [phutchins/logstash-input-mongodb#22]
Hi @phutchins ,

I tried using logstash-input-mongodb-0.2.0 for syncing mongodb data with ES.

However when we remove documents in mongoldb corresponding documents are not getting removed from ES.

Is this known issue or expected behaviour.

Please let us know how to resolve this issue if already fixed.

regards,
chakrapani

**Comment by phutchins** [comment]
This is expected behavior. There would have to be quite a bit more logic added to handle this case.

My use case was for parsing logs from mongo to Elasticsearch so there was no need to check if entries were deleted. It only sync's going forward.

Do you mind sharing your use case?

**Comment by phutchins** [comment]
Closing this as this is expected behavior... If you have ideas around how this could be accomplished or would like to submit a pull request to add this as a feature, I'd be happy to entertain the idea.

**Comment by RdrgPorto** [comment]
Hi @chakrip82 
You could try with Mongo Connector : https://github.com/mongodb-labs/mongo-connector
There is a article which you can learn how to use it : https://blog.jixee.me/how-to-use-mongo-connector-with-elasticsearch/
Good Luck!!
