### ISSUE TITLE
No connection string specified Error

### ISSUE THREAD

**Issue by Vinoth28** [phutchins/logstash-input-mongodb#6]
The error i get is-
![untitled](https://cloud.githubusercontent.com/assets/13480367/9218201/e7a6cdd4-40ed-11e5-9a5e-ffb2cc063730.png)

My config file is
![untitled1](https://cloud.githubusercontent.com/assets/13480367/9218205/f68953f8-40ed-11e5-94ba-289bf5ea0f9f.png)

and what does the PATH specify in conf file. can you please explain it.

**Comment by phutchins** [comment]
Looks like this may be an issue with jruby in windows.

Check out the bug report here...
https://github.com/jruby/jruby/issues/1614

You may want to contribute to the thread.

**Comment by Vinoth28** [comment]
Thank you for the reply, but I think the discussion is still going on there and i haven't found a solution yet. may i know what does the Path specify in the conf file. what does that logstash_sqlite.db refers to. where to find that file actually.

**Comment by Vinoth28** [comment]
facing an error like this now by using the new gem

![image](https://cloud.githubusercontent.com/assets/13480367/9268428/7695981a-427c-11e5-86b1-982ffa6a94b2.png)

**Comment by phutchins** [comment]
@Vinoth28 , the logstash_sqlite.db file is a very small database. It is created by the input-mongodb plugin and it is used to keep track of, or bookmark the last processed documents from mongo. You do not need to create it, simply provide a directory that logstash can write to and specify the desired file.

I'll update the documentation to make it a bit more clear on that...

I working on getting the install working for all users then I'll jump back on this and see if I can help more...

**Comment by Vinoth28** [comment]
![image](https://cloud.githubusercontent.com/assets/13480367/9299128/252a17b0-44d6-11e5-87b4-d77290ad04fc.png)

I am getting this error but i have specified the URI still getting this error. can you help me to resolve it.

**Comment by phutchins** [comment]
@Vinoth28 could you provide your config please?

**Comment by Vinoth28** [comment]
This is my conf file

![image](https://cloud.githubusercontent.com/assets/13480367/9355463/247a8134-4697-11e5-956d-12e78ba9c4ed.png)

**Comment by Vinoth28** [comment]
with the new version i get this error. 
![pastedimage](https://cloud.githubusercontent.com/assets/13480367/9355498/8e5dc818-4697-11e5-96a4-ab173d906d4c.png)

**Comment by phutchins** [comment]
Your config looks correct. What does the mongo log say on the other side?

Assuming you're not using SSL with mongo?

**Comment by Vinoth28** [comment]
Is it necessary to use SSL with mongo to get it working?

**Comment by phutchins** [comment]
It should not be but my use case uses SSL so there is a chance that my logic doesn't work well with non ssl. Did you get this working? If not I'll take a look and test without SSL.

**Comment by phutchins** [comment]
I've tried this without SSL and it seems to work fine for me. I've got another issue that I'm looking at where we simplify the uri and ssl. After that is complete, let me know if you're still having issues. Closing as this has been dead for a while.
