### ISSUE TITLE
Work around for error raised when installing?

### ISSUE THREAD

**Issue by deepvoice** [phutchins/logstash-input-mongodb#7]
(EDIT) Error has changed after mucking with it - first issue was my fault.

\# bin/plugin install logstash-input-mongodb
LoadError: no such file to load -- file-dependencies/gem
  require at org/jruby/RubyKernel.java:1072
  require at /local/logstash-1.5.3/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
   (root) at /local/logstash/lib/pluginmanager/install.rb:4
  require at org/jruby/RubyKernel.java:1072
   (root) at /local/logstash-1.5.3/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at /local/logstash-1.5.3/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54

**Comment by phutchins** [comment]
Hey @deepvoice did you run the bootstrap command to bootstrap logstash?

```
rake bootstrap
```

Make sure you've carried out all of the steps listed on the logstash github page for installing a plugin via this method.

https://github.com/elastic/logstash

**Comment by phutchins** [comment]
@deepvoice Is the error in the first post your most recent error? Its best to post edits in new comments so I can keep track of our progress...

Maybe this is similar to your issue?
http://stackoverflow.com/questions/26360657/many-require-cannot-load-such-file-gem-name-loaderror-after-upgrade-o

**Comment by phutchins** [comment]
Spec file has been updated and haven't heard back so I assume this is fixed. Please let me know if this is not the case. Closing.
