### ISSUE TITLE
Field [_id] is a metadata field and cannot be added inside a document

### ISSUE THREAD

**Issue by TaurusD** [phutchins/logstash-input-mongodb#70]
I'm using Elasticsearch 5.4, Logstash 5.4.2, MongoDB 3.4.5. 
When I import from MongoDB to Elasticsearch through Logstash, I found the following error: 

`[2017-07-11T16:57:06,180][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"mongodb-2017.07.11", :_type=>"logs", :_routing=>nil}, 2017-07-11T08:57:03.744Z %{message}], :response=>{"index"=>{"_index"=>"mongodb-2017.07.11", "_type"=>"logs", "_id"=>"AV0w3bobj2yUz3xTJdU4", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters."}}}}`

It mentioned that there was a conflict between the name of [_id] meta field in Kibana and [_id] meta column of MongoDB. How should I solve this conflict in my logstash pipeline config? I think this is a critical problem between ES and Mongo, how did this plugin work before? 

Thank you!

**Comment by TaurusD** [comment]
My logstash config: 

`input {
	mongodb {
		uri => 'mongodb://localhost:27017/heat'
		placeholder_db_dir => 'D:/MongoDB/test/Logstash_test/logstash-mongodb/'
		placeholder_db_name => 'logstash_sqlite_heat.db'
		collection => 'Export_4G_Cell_20170710105046944'
		batch_size => 5000
	}
}
output {
	elasticsearch {
        hosts => [ "localhost:9200" ]
		index => "mongodb-%{+YYYY.MM.dd}"
    }
}`

**Comment by TaurusD** [comment]
Well, I'm back for this short moment cause I solved the above problem by just changing the column name from [_id] to other names with mutate filter. 
And I found another problem after I imported data. Please let me close this issue and open another one for a different topic. 
Thanks.

**Comment by manojsb** [comment]
@TaurusD  Can you explain please how did you make it work ? and how did you setup this ?

**Comment by TaurusD** [comment]
@manojsb Hi, I just used `mutate` filter like this: 

`filter {
	mutate{
		rename => ["_id", "Obj_id"]
	}
}`

This may import the data from `_id` in Mongo to `Obj_id` field in Elasticsearch, so there won't be any conflict with the meta field [_id] of Elasticsearch. `Obj_id` is a field you can define by yourself. 
In fact, I noticed that this mongo-input plugin do copy the `_id` column to a new field called [mongo_id] while importing, but it may 'forget' to remove import the original `_id` so that it caused conflict.

**Comment by manojsb** [comment]
@TaurusD  thank you so much for explanation.  Just one more question are using it in production?

**Comment by TaurusD** [comment]
@manojsb no, I just use it for some testing. no production

**Comment by manojsb** [comment]
@TaurusD thanks for feedback

**Comment by ansballard** [comment]
Just ran into this as well. `parse_method => "dig"` correctly ignores the _id field, since it has an explicit check at [Line 317](https://github.com/phutchins/logstash-input-mongodb/blob/master/lib/logstash/inputs/mongodb.rb#L317). A fix would be pretty straightforward, just need to add the same check to the `flatten` and `simple` parse_methods. For now I'm going to use `dig`, since I'm mostly researching at this point.
