### ISSUE TITLE
Infinite loop adding mongoDB documents into ElasticSearch

### ISSUE THREAD

**Issue by CarlitoxxPro** [phutchins/logstash-input-mongodb#9]
We use this logstash configuration:

input {
  mongodb {
    uri => 'mongodb://127.0.0.1/test'
    placeholder_db_dir => '/users/sth00/logstash-mongodb/'
    placeholder_db_name => 'logstash_sqlite.db'
    collection => 'Users'
    batch_size => 5000
  }
}
output {
  stdout { codec => rubydebug }
  elasticsearch {
    host => "127.0.0.1"
    protocol => "http"
    index => "mongodb-%{+YYYY.MM.dd}"
  }
}

in mongoDB the collection "Users" only have 4 fields: _id, name, email, age
we have only 7 records and in elasticsearch these 7 records have been duplicate every second and it doesn't stop. why?

Among other things, how I can delete the fileds: logdate and logentry, we only need dump the mongodb data (Fields) into ES and keep synced these data between mongoDB and ES thanks to logstash and the plugin.

cordial regards

**Comment by jatanpatel92** [comment]
Did you find the solution of this problem? Actually I am having the same issue.

**Comment by CarlitoxxPro** [comment]
not until now, but when I have some time, I try to analize some code to see if I can make it work properly.

**Comment by CarlitoxxPro** [comment]
the proposal fix is:

Edit the file: vendor/local_gems/9d72c2a4/logstash-input-mongodb-0.2.0/lib/logstash/inputs/mongodb.rb

search this line: return collection.find({:_id => {:$gte* => last_id_object}}).limit(batch_size)

and replace $gte (greater than or equal) by $gt (greater than)

and the problem is solved.
Thanks to @snagajot

**Comment by snagajot** [comment]
@CarlitoxxPro Thanks for the tip. I was able to make the changes and it worked.

But.. there arises an issue when it is the first time querying a mongo DB. The first document will be skipped since $gt of the first element's _id will give you second document onwards. Any thoughts on how to fix this ? One way is to use '$eq' if it is the first element (if no existing last_id in sqllite db) and $gt (is there is a last_id in sqllite db) from the second element and forward. 

Thanks

**Comment by snagajot** [comment]
Also, if you want logstash to stop once all documents are read from Mongo (and not be in a loop waiting for updates) comment the following lines in mongodb.rb.

lines 225-227,232,344-348

**Comment by CarlitoxxPro** [comment]
In my test, I only change this ($gte by $gt), flushing the since.db of logstash, use a new mongo database with 5 entries, inserting directly in elasticsearch.

when I start logstash, this put the 5 entries into elasticsearch correctly, after this I insert more entries into mongo db manually and the logstash get and put in elasticsearch as well.

if i stop the logstash and run again, logstash waiting for new changes.

Note that the plugin is unable to update the entries in elasticsearch
if we change an entry field in mongo db, logstash makes no action (not inserted as a new change and not updated)

Versions: Logstash 1.5.4 + Elasticsearch 1.7.1 + MongoDB 3.0.6

**Comment by phutchins** [comment]
The MR associated with this has been merged so I'm closing this one. Please feel free to comment if you have additional questions or concerns. Thanks for the input!

**Comment by RihabTlili** [comment]
Hello,
I have the same problem, I try to load data from mongodb to logstash but I have Infinite loop.
I use logstash 1.5.4 and mongo db 3.5.1.

My logstash configuration :

input {
mongodb {
uri => "mongodb://127.0.0.1:27017/logtest"
collection => "products"
placeholder_db_dir => 'c:/elk2/'
placeholder_db_name => 'logstash_sqlite.db'
batch_size => 1
}
}

output {
stdout { codec => rubydebug }
file {
path => "C:\elk\out.log"
}
}

This is the out put. it's an infinite loop and the data is not loaded.

D, [2018-04-18T16:41:29.295000 #9192] DEBUG -- : MONGODB | 127.0.0.1:27017 | log
test.find | SUCCEEDED | 0.007s
D, [2018-04-18T16:41:29.338000 #9192] DEBUG -- : MONGODB | 127.0.0.1:27017 | log
test.listCollections | STARTED | {"listCollections"=>1, "cursor"=>{}, "filter"=>
{"name"=>{"$not"=>/system.|$/}}}
D, [2018-04-18T16:41:29.347000 #9192] DEBUG -- : MONGODB | 127.0.0.1:27017 | log
test.listCollections | SUCCEEDED | 0.006s

Thank you in advance, 
cordial regards
